"on":
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - labeled
name: Change File Included in PR
jobs:
  check-files-in-directory:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'Release Not Needed') && !contains(github.event.pull_request.labels.*.name, 'Release PR') }}
    runs-on: ubuntu-latest
    name: Change File Included in PR
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      name: Checkout PR code
    - uses: tj-actions/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf
      id: changed-files
      name: Get List of Changed Files
    - run: |
        DIRECTORY=".autover/changes/"
        if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -q "$DIRECTORY"; then
          echo "✅ One or more change files in '$DIRECTORY' are included in this PR."
        else
          echo "❌ No change files in '$DIRECTORY' are included in this PR."
          echo "Refer to the 'Adding a change file to your contribution branch' section of https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/CONTRIBUTING.md"
          exit 1
        fi
      name: Check for Change File(s) in .autover/changes/
